  function autocomplete(inp, arr) {
    /*the autocomplete function takes two arguments,
    the text field element and an array of possible autocompleted values:*/
    var currentFocus;
    /*execute a function when someone writes in the text field:*/
    inp.addEventListener("input", function(e) {
        var a, b, i, val = this.value;
        /*close any already open lists of autocompleted values*/
        closeAllLists();
        if (!val) { return false;}
        currentFocus = -1;
        /*create a DIV element that will contain the items (values):*/
        a = document.createElement("DIV");
        a.setAttribute("id", this.id + " autocomplete-list");
        a.setAttribute("class", "autocomplete-items");
        /*append the DIV element as a child of the autocomplete container:*/
        this.parentNode.appendChild(a);
        /*for each item in the array...*/
        for (i = 0; i < arr.length; i++) {
          /*check if the item starts with the same letters as the text field value:*/
          if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
            /*create a DIV element for each matching element:*/
            b = document.createElement("DIV");
            /*make the matching letters bold:*/
            b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
            b.innerHTML += arr[i].substr(val.length);
            /*insert a input field that will hold the current array item's value:*/
            b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
            /*execute a function when someone clicks on the item value (DIV element):*/
            b.addEventListener("click", function(e) {
                /*insert the value for the autocomplete text field:*/
                inp.value = this.getElementsByTagName("input")[0].value;
                /*close the list of autocompleted values,
                (or any other open lists of autocompleted values:*/
                closeAllLists();
            });
            a.appendChild(b);
          }
        }
    });
    /*execute a function presses a key on the keyboard:*/
    inp.addEventListener("keydown", function(e) {
        var x = document.getElementById(this.id + " autocomplete-list");
        if (x) x = x.getElementsByTagName("div");
        if (e.keyCode == 40) {
          /*If the arrow DOWN key is pressed,
          increase the currentFocus variable:*/
          currentFocus++;
          /*and and make the current item more visible:*/
          addActive(x);
        } else if (e.keyCode == 38) { //up
          /*If the arrow UP key is pressed,
          decrease the currentFocus variable:*/
          currentFocus--;
          /*and and make the current item more visible:*/
          addActive(x);
        } else if (e.keyCode == 13) {
          /*If the ENTER key is pressed, prevent the form from being submitted,*/
          e.preventDefault();
          if (currentFocus > -1) {
            /*and simulate a click on the "active" item:*/
            if (x) x[currentFocus].click();
          }
        }
    });
    function addActive(x) {
      /*a function to classify an item as "active":*/
      if (!x) return false;
      /*start by removing the "active" class on all items:*/
      removeActive(x);
      if (currentFocus >= x.length) currentFocus = 0;
      if (currentFocus < 0) currentFocus = (x.length - 1);
      /*add class "autocomplete-active":*/
      x[currentFocus].classList.add("autocomplete-active");
    }
    function removeActive(x) {
      /*a function to remove the "active" class from all autocomplete items:*/
      for (var i = 0; i < x.length; i++) {
        x[i].classList.remove("autocomplete-active");
      }
    }
    function closeAllLists(elmnt) {
      /*close all autocomplete lists in the document,
      except the one passed as an argument:*/
      var x = document.getElementsByClassName("autocomplete-items");
      for (var i = 0; i < x.length; i++) {
        if (elmnt != x[i] && elmnt != inp) {
          x[i].parentNode.removeChild(x[i]);
        }
      }
    }
    /*execute a function when someone clicks in the document:*/
    document.addEventListener("click", function (e) {
        closeAllLists(e.target);
    });
  }

  var makes = [
    "Adam",
    "Aeroprakt",
    "Aerospatiale",
    "AgustaWestland",
    "Airbus",
    "Antonov",
    "Aquila",
    "Avions Robin",
    "Avro International Aerospace",
    "Beechcraft",
    "Bell",
    "Beriev Aircraft Company",
    "Boeing",
    "Bombardier",
    "British Aerospace",
    "British Aircraft Corporation",
    "Britten-Norman",
    "CAIC",
    "Cessna",
    "Champion Aircraft Corporation",
    "Cirrus",
    "Convair",
    "Curtiss-Wright",
    "Dassault Falcon",
    "De Havilland Aircraft of Canada",
    "Denel Aviation",
    "Diamond Aircraft Industries",
    "Dornier Luftfahrt",
    "Embraer",
    "Enstrom Helicopter",
    "Eurocopter",
    "Evektor-Aerotechnik",
    "Fokker",
    "GippsAero",
    "Government Aircraft Factories",
    "Grumman",
    "Gulfstream",
    "Harbin Aircraft Industry Group",
    "Hawker",
    "Hindustan Aeronautics Limited",
    "Honda",
    "ICON",
    "Ilyushin",
    "Indonesian Aerospace",
    "Israel Aircraft Industries",
    "Junkers",
    "Kaman Aerospace",
    "Kamov",
    "Kazan Helicopters",
    "Learjet",
    "Let Kunovice",
    "Lockheed Corporation",
    "McDonnell Douglas",
    "MD Helicopters",
    "MIL Helicopters",
    "Mil Moscow Helicopter Plant",
    "Mitsubishi",
    "NH Industries",
    "Piaggio Aero",
    "Pilatus Aircraft",
    "Piper Aircraft",
    "Pipistrel",
    "PZL Swidnik",
    "Robinson Helicopter",
    "Rotorway",
    "Saab",
    "Short Brothers",
    "Sikorsky",
    "Socata",
    "Sukhoi",
    "Team Rocket",
    "Tecnam",
    "TL Ultralight",
    "Tupolev",
    "Vulcanair",
    "Yakovlev"
  ];

  /*An array containing all the country names in the world:*/
  var makesFull = [
    "3XTRIM",
    "A-41",
    "AAC",
    "AAK",
    "AAMSA",
    "AASI",
    "ABHCO",
    "ABS",
    "ABS AEROLIGHT",
    "ACBA",
    "ACE",
    "ACEAIR",
    "ACES HIGH",
    "ACRO SPORT",
    "ACS",
    "AD AEROSPACE",
    "ADA",
    "ADAM",
    "ADAMS",
    "ADVANCED AEROMARINE",
    "ADVANCED AIRCRAFT",
    "ADVANCED AVIATION",
    "ADVENTURE AIR",
    "AEA",
    "AERFER-AERMACCHI",
    "AERITALIA",
    "AERITALIA-AERMACCHI",
    "AERMACCHI",
    "AERO",
    "AERO ADVENTURE",
    "AERO BOERO",
    "AERO COMMANDER",
    "AERO DESIGNS",
    "AERO ELI",
    "AERO GARE",
    "AERO ITBA",
    "AERO JAEN",
    "AERO KUHLMANN",
    "AERO MERCANTIL",
    "AERO MIRAGE",
    "AERO MOD",
    "AERO SERVICES",
    "AERO SPACELINES",
    "AEROALCOOL",
    "AEROANDINA",
    "AERO-ASTRA",
    "AEROBRAVO",
    "AEROCAD",
    "AEROCAR",
    "AEROCOMP",
    "AERO-COMPOSITES",
    "AERO-DIFUSION",
    "AERODIS",
    "AERODYNOS",
    "AERO-EAST-EUROPE",
    "AEROJAMES",
    "AERO-JODEL",
    "AEROKOPTER",
    "AERO-KROS",
    "AEROLAB",
    "AEROLITES",
    "AEROMERE",
    "AEROMOT",
    "AERONCA",
    "AERONIX",
    "AEROPLASTIKA",
    "AEROPRACT",
    "AEROPRAKT",
    "AEROPRO",
    "AEROPROGRESS",
    "AEROPUP",
    "AERORIC",
    "AEROS",
    "AEROSAMARA",
    "AEROSETTE",
    "AEROSPATIALE",
    "AEROSPOOL",
    "AEROSPORT",
    "AEROSTAR",
    "AEROSTRUCTURE",
    "AEROSTYLE",
    "AEROTEC",
    "AEROTECH",
    "AEROTECHNIK",
    "AEROTEK",
    "AEROTREK",
    "AEROVOLGA",
    "AESL",
    "AFIC",
    "AG-CAT",
    "AGRO-COPTEROS",
    "AGROLOT",
    "AGUSTA",
    "AGUSTAWESTLAND",
    "AI(R)",
    "AIAA",
    "AICSA",
    "AIDC",
    "AIEP",
    "AII",
    "AIL",
    "AIR",
    "AIR & SPACE",
    "AIR COMMAND",
    "AIR PARTS",
    "AIR PRODUCTS",
    "AIR TRACTOR",
    "AIRBUS",
    "AIRBUS HELICOPTERS",
    "AIRBUS HELICOPTERS-HARBIN",
    "AIRBUS HELICOPTERS-KAWASAKI",
    "AIRCONCEPT",
    "AIRCRAFT DESIGNS",
    "AIRCRAFT HYDRO-FORMING",
    "AIRCRAFT INDUSTRIES",
    "AIRCRAFT PARTS",
    "AIRCRAFT SPRUCE",
    "AIRCRAFT TECHNOLOGIES",
    "AIRDALE",
    "AIRDROME AEROPLANES",
    "AIR-FOUGA",
    "AIRFRAMES",
    "AIRFRAMES-DAKOTA CUB",
    "AIR-LIGHT",
    "AIRLONY",
    "AIRMASTER",
    "AIRMAX",
    "AIRO",
    "AIRPLANE FACTORY",
    "AIRSPORT",
    "AIRTECH",
    "AISA",
    "AJEP",
    "AJI",
    "AKAFLIEG BERLIN",
    "AKAFLIEG DARMSTADT",
    "AKAFLIEG KARLSRUHE",
    "AKAFLIEG MUNCHEN",
    "AKRON",
    "AKROTECH",
    "AKROTECH EUROPE",
    "ALANNE",
    "ALENIA",
    "ALENIA AERMACCHI",
    "ALEXANDRIA",
    "ALFA-M",
    "ALLISON",
    "ALMS",
    "ALON",
    "ALPAERO",
    "ALPAVIA",
    "ALPHA",
    "ALPHA AVIATION",
    "ALPI",
    "ALPLA",
    "ALTAIR COELHO",
    "ALTURAIR",
    "ALVAREZ",
    "AMAX",
    "AMBROSINI",
    "AMC",
    "AMD",
    "AMEAGLE",
    "AMERICAN",
    "AMERICAN AFFORDABLE",
    "AMERICAN AIRCRAFT",
    "AMERICAN AUTOGYRO",
    "AMERICAN CHAMPION",
    "AMERICAN EAGLE",
    "AMERICAN GENERAL",
    "AMERICAN HOMEBUILTS",
    "AMERICAN LEGEND",
    "AMERICAN SPORTSCOPTER",
    "AMEUR",
    "AMS-FLIGHT",
    "AMX",
    "ANAHUAC",
    "ANDERSON",
    "ANDERSON-GREENWOOD",
    "ANDREASSON",
    "ANGEL",
    "ANGLIN",
    "ANGLO NORMANDY",
    "ANTONIEWSKI",
    "ANTONOV",
    "AOI",
    "APPLEBAY",
    "APPLEGATE & WEYANT",
    "AQUILA",
    "ARADO",
    "ARC ATLANTIQUE",
    "ARC-41",
    "ARCTIC",
    "ARDC",
    "ARION",
    "ARMSTRONG WHITWORTH",
    "ARNET PEREYRA",
    "ARROW",
    "ARROW (2)",
    "ARV",
    "ASAP",
    "ASL",
    "ASSO AEREI",
    "ASSOCIATED AIR",
    "ASTA",
    "ATAC",
    "ATEC",
    "ATG",
    "ATLAS",
    "ATR",
    "AUSTER",
    "AUSTFLIGHT",
    "AUSTRALIAN AEROSPACE",
    "AUSTRALITE",
    "AUTOGYRO",
    "AVANTAGE",
    "AVCRAFT",
    "AVEKO",
    "AVIA",
    "AVIA BALTIKA",
    "AVIABELLANCA",
    "AVIADESIGN",
    "AVIAIMPEX",
    "AVIAKIT",
    "AVIAMILANO",
    "AVIASTROITEL",
    "AVIAT",
    "AVIATECH",
    "AVIATIKA",
    "AVIATIK-ALYANS",
    "AVIATION DEVELOPMENT",
    "AVIATION ENTERPRISES",
    "AVIATION FARM",
    "AVIATION SCOTLAND",
    "AVIATION TRADERS",
    "AVIATON",
    "AVICOPTER",
    "AVID",
    "AVIOANE",
    "AVION",
    "AVIONES COLOMBIA",
    "AVIONS FAIREY",
    "AVIOTECHNICA",
    "AVIOTECNICA",
    "AVIPRO",
    "AVRO",
    "AVTEK",
    "AYRES",
    "B & F TECHNIK",
    "BAC",
    "BACAU",
    "BACKCOUNTRY",
    "BAE SYSTEMS",
    "BAE SYSTEMS AUSTRALIA",
    "BAKENG",
    "BARNETT",
    "BARR",
    "BASLER",
    "BD-MICRO",
    "BEACHNER",
    "BEAGLE",
    "BEAGLE-AUSTER",
    "BEDE",
    "BEECH",
    "BEECHCRAFT",
    "BEECH-SFERMA",
    "BEETS",
    "BEIJING KEYUAN",
    "BEL-AIRE",
    "BELL",
    "BELL-AGUSTA",
    "BELLANCA",
    "BELL-BOEING",
    "BENGIS",
    "BERIEV",
    "BERKUT",
    "BEST OFF",
    "BHARAT",
    "BILLIE",
    "BILSAM",
    "BINDER",
    "BITZ",
    "BLACKBURN",
    "BLERIOT",
    "BLUE YONDER",
    "BOEING",
    "BOEING CANADA",
    "BOEING VERTOL",
    "BOEVE",
    "BOISAVIA",
    "BOLKOW",
    "BOMBARDIER",
    "BOT AIRCRAFT",
    "BOWERS",
    "BRADLEY",
    "BRANDLI",
    "BRANTLY",
    "BRANTLY-HYNES",
    "BRDITSCHKA",
    "BREDANARDI",
    "BREEZER",
    "BREGUET",
    "BRIAN ALLEN",
    "BRISTOL",
    "BRITISH AEROSPACE",
    "BRITTEN-NORMAN",
    "BRM AERO",
    "BROKAW",
    "BROOKLANDS",
    "BRUMBY",
    "BUCHANAN",
    "BUCKER",
    "BUCKER PRADO",
    "BUCURESTI",
    "BUETHE",
    "BUHL",
    "BUL",
    "BUSHBY",
    "BUTTERFLY",
    "C2P",
    "CAARP",
    "CAB",
    "CABLE-PRICE",
    "CABRINHA",
    "CADCOR",
    "CAG",
    "CALLAIR",
    "CALUMET",
    "CAMAIR",
    "CAMERON",
    "CAMPANA",
    "CANADA AIR RV",
    "CANADAIR",
    "CANADIAN HOME ROTORS",
    "CANADIAN VICKERS",
    "CAP AVIATION",
    "CAPELLA",
    "CAPRONI VIZZOLA",
    "CARLSON",
    "CARRIOU",
    "CARTER",
    "CASA",
    "CASSUTT",
    "CATA",
    "CAUDRON",
    "CCF",
    "CEA",
    "CEI",
    "CELAIR",
    "CELIER",
    "CENTRE EST",
    "CENTURY",
    "CERVA",
    "CESSNA",
    "CFM",
    "CHAIKA",
    "CHALARD",
    "CHAMPION",
    "CHANCE VOUGHT",
    "CHANGHE",
    "CHASLE",
    "CHAYAIR",
    "CHENGDU",
    "CHERNOV",
    "CHICHESTER-MILES",
    "CHILTON",
    "CHINCUL",
    "CHRIS TENA",
    "CHRISTEN",
    "CIAC",
    "CICARE",
    "CIRCA",
    "CIRRUS",
    "CLAASSEN",
    "CLASS",
    "CLASSIC",
    "CLASSIC SPORT",
    "CLAUDIUS DORNIER",
    "CLIFFORD AEROWORKS",
    "COBALT",
    "COBELAVIA",
    "COBRA",
    "COLEMILL",
    "COLLINS",
    "COLOMBAN",
    "COLONIAL",
    "COLUMBIA",
    "COLYAER",
    "COMAC",
    "COMMANDER",
    "COMMONWEALTH",
    "COMP AIR",
    "COMPOSIT AIRPLANES",
    "CONAIR",
    "CONROY",
    "CONSOLIDATED",
    "CONTINENTAL COPTERS",
    "CONVAIR",
    "COOPAVIA",
    "COOPAVIA-MENAVIA",
    "CORBEN",
    "CORBY",
    "CORVUS",
    "COSY",
    "COUNTRY AIR",
    "COUPE",
    "CO-Z",
    "CRAE",
    "CRAIOVA",
    "CRANFIELD",
    "CREATIVE FLIGHT",
    "CROSES",
    "CSA",
    "CSS",
    "CTRM",
    "CUB",
    "CUB CRAFTERS",
    "CULP",
    "CULVER",
    "CURTISS",
    "CUSTOM FLIGHT",
    "CVJETKOVIC",
    "CZAW",
    "DAC",
    "DAEWOO",
    "DAKOTA CUB",
    "DALLACH",
    "DALLAIR",
    "DAMOURE-FABRE",
    "D'APUZZO",
    "DART",
    "DASA",
    "DASSAULT",
    "DASSAULT-DORNIER",
    "DATWYLER",
    "DAVIS",
    "DE HAVILLAND",
    "DE HAVILLAND AUSTRALIA",
    "DE HAVILLAND CANADA",
    "DE SCHELDE",
    "DEAN-WILSON",
    "DEBORDE-ROLLAND",
    "DELISLE",
    "DENEL",
    "DENIZE",
    "DENNEY",
    "DERAZONA",
    "DERRINGER",
    "DESJARDINS",
    "DEWOITINE",
    "DF HELICOPTERS",
    "DG FLUGZEUGBAU",
    "DIAMOND",
    "DICKEY",
    "DIJKMAN-DULKES",
    "DINFIA",
    "DIRECT FLY",
    "DIRGANTARA",
    "DISTAR",
    "DM AEROSPACE",
    "DORNA",
    "DORNIER",
    "DOUGLAS",
    "DOVA",
    "DOWNER",
    "DRAGON FLY",
    "DREAM",
    "DRIGGS",
    "DRUINE",
    "DUBNA",
    "DURAND",
    "DURUBLE",
    "DYKE",
    "DYN'AERO",
    "DYNALI",
    "E & K",
    "E-7 GROUP",
    "EAA",
    "EAC",
    "EADS",
    "EAGLE",
    "EAGLE AIRCRAFT",
    "EAGLE AVIATION",
    "EARLY BIRD",
    "ECLIPSE",
    "ECTOR",
    "EDGAR PERCIVAL",
    "EDGLEY",
    "EDRA",
    "EGVOYAGER",
    "EHI",
    "EICH",
    "EIRI",
    "EIS",
    "EKOLOT",
    "EKW",
    "ELA AVIACION",
    "ELBIT",
    "ELITAR",
    "ELLISON-MAHON",
    "ELMWOOD",
    "EMAIR",
    "EMBRAER",
    "EMIVEST",
    "EMROTH",
    "ENAER",
    "ENGLISH ELECTRIC",
    "ENSTROM",
    "EPERVIER",
    "EPIC AIRCRAFT",
    "ERCO",
    "ERPALS",
    "ETA AIRCRAFT",
    "ETHIOPIAN AIRLINES",
    "EURO PINGOUIN",
    "EUROALA",
    "EUROCOPTER",
    "EUROCOPTER-HARBIN",
    "EUROCOPTER-KAWASAKI",
    "EURODISPLAY",
    "EURO-ENAER",
    "EUROFIGHTER",
    "EURO-FLY",
    "EURONEF",
    "EUROPA",
    "EUROSPACE",
    "EVANGEL",
    "EVANS",
    "EVEKTOR",
    "EVEKTOR-AEROTECHNIK",
    "EXCALIBUR",
    "EXCEL-JET",
    "EXCLUSIVE",
    "EXPERIMENTAL AVIATION",
    "EXPLORER",
    "EXPRESS",
    "EXTRA",
    "F+W EMMEN",
    "FAIRCHILD",
    "FAIRCHILD DORNIER",
    "FAIRCHILD HILLER",
    "FAIRCHILD SWEARINGEN",
    "FAIREY",
    "FAIRTRAVEL",
    "FAJR",
    "FALCOMPOSITE",
    "FALCONAR",
    "FAMA",
    "FANTASY AIR",
    "FARIGOUX",
    "FARNBOROUGH",
    "FARRINGTON",
    "FD-COMPOSITES",
    "FEUGRAY",
    "FFA",
    "FFT",
    "FIAT",
    "FIESELER",
    "FIGHTER ESCORT WINGS",
    "FIKE",
    "FINMECCANICA",
    "FISHER",
    "FISHER AERO",
    "FLAGLOR",
    "FLAIR",
    "FLÄMING AIR",
    "FLEET",
    "FLETCHER",
    "FLIGHT DESIGN",
    "FLIGHT ENGINEERS",
    "FLIGHTWORKS",
    "FLITZER",
    "FLS",
    "FLSZ",
    "FLUG WERK",
    "FLY SYNTHESIS",
    "FLYER",
    "FLYGFABRIKEN",
    "FLYING MACHINES",
    "FLYITALIA",
    "FMA",
    "FMP",
    "FOCKE-WULF",
    "FOKKER",
    "FOLLAND",
    "FORD",
    "FORNAIRE",
    "FORNEY",
    "FOUGA",
    "FOUND",
    "FOUR WINDS",
    "FOURNIER",
    "FOXCON",
    "FRAKES",
    "FREE SPIRIT",
    "FREEDOM",
    "FREEDOM MASTER",
    "FREEWING",
    "FRONTIER",
    "FRY",
    "FUJI",
    "FUNK",
    "G1 AVIATION",
    "GAF",
    "GANNET",
    "GANZAVIA",
    "GARDAN",
    "GARLAND",
    "GARRISON",
    "GATARD",
    "GATES LEARJET",
    "GAVILAN",
    "GENERAL AIRCRAFT",
    "GENERAL ATOMICS",
    "GENERAL AVIA",
    "GENERAL DYNAMICS",
    "GENERAL MOTORS",
    "GERMAN BIANCO",
    "GILES",
    "GIPPSAERO",
    "GIPPSLAND",
    "GLASAIR",
    "GLASER-DIRKS",
    "GLASS",
    "GLASSIC",
    "GLOBAL",
    "GLOBE",
    "GLOSTER",
    "GM&T",
    "GOAIR",
    "GOBOSH",
    "GOLDEN CAR",
    "GOLDEN CIRCLE",
    "GOMOLZIG",
    "GOODYEAR",
    "GÖTAVERKEN",
    "GREAT LAKES",
    "GREAT PLAINS",
    "GREGA",
    "GRIFFON",
    "GRIFFON AERO",
    "GRINVALDS",
    "GROB",
    "GROEN",
    "GROPPO",
    "GROSSO",
    "GROVE",
    "GROVER",
    "GRUMMAN",
    "GRUMMAN AMERICAN",
    "GRYF",
    "GUERIN",
    "GUIMBAL",
    "GUIZHOU",
    "GULFSTREAM",
    "GYROFLUG",
    "HAGGLUND",
    "HAINZ",
    "HALBERSTADT",
    "HALLEY",
    "HALSTED",
    "HAMILTON",
    "HANDLEY PAGE",
    "HAPI",
    "HARBIN",
    "HARMON",
    "HAT",
    "HATZ",
    "HAWKER",
    "HAWKER BEECHCRAFT",
    "HAWKER DE HAVILLAND",
    "HAWKER SIDDELEY",
    "HB-AIRCRAFT",
    "HB-FLUGTECHNIK",
    "HEINKEL",
    "HEINTZ",
    "HELIBRAS",
    "HELICOM",
    "HELIO",
    "HELIOPOLIS",
    "HELIPRO",
    "HELI-SPORT",
    "HELIVERT",
    "HELOWERKS",
    "HELWAN",
    "HENDERSON",
    "HESA",
    "HFB",
    "HIGHER CLASS",
    "HIGHLANDER",
    "HILLBERG",
    "HILLER",
    "HINDUSTAN",
    "HIRTH",
    "HISPANO",
    "HK",
    "HOAC",
    "HOFFMANN",
    "HOLCOMB",
    "HOLLMANN",
    "HONDA",
    "HONDA-MISSISSIPPI",
    "HONGDU",
    "HONGDU MD HELICOPTERS",
    "HOVEY",
    "HOWARD",
    "HPA",
    "HUGHES",
    "HUMBERT",
    "HUMMEL",
    "HUNTING",
    "HUNTING PERCIVAL",
    "HUREL-DUBOIS",
    "HUZHOU TAIXIANG",
    "HYDROPLANE",
    "HYNES",
    "HYUNDAI",
    "IAI",
    "IANNOTTA",
    "IAR",
    "IBIS",
    "ICA",
    "ICON",
    "ICP",
    "IDEA",
    "IFB",
    "III",
    "IKAR",
    "IKARUS",
    "ILYUSHIN",
    "IMCO",
    "IMP",
    "IMPULSE",
    "INDAER CHILE",
    "INDAER PERU",
    "INDEPENDENT",
    "INDUS",
    "INNOVATION",
    "INPAER",
    "INSTYTUT LOTNICTWA",
    "INTER-AIR",
    "INTERAVIA",
    "INTERNATIONAL HELICOPTERS",
    "INTERPLANE",
    "INTERSTATE",
    "INTRACOM",
    "ION",
    "IPAI",
    "IPE",
    "IPT",
    "IRGC",
    "IRIAF",
    "IRKUT",
    "IRMA",
    "ISAACS",
    "ISAE",
    "ISLAND AIRCRAFT",
    "ISRAVIATION",
    "ISSOIRE",
    "ISTRA",
    "J & AS",
    "JABIRU",
    "JACKAROO",
    "JAG HELICOPTER",
    "JAMES",
    "JANOWSKI",
    "JAVELIN",
    "JEFFAIR",
    "JETCRAFTERS",
    "JETPROP",
    "JETSTREAM",
    "JIANGXI CHANGHE-AGUSTA",
    "JIHLAVAN",
    "JODEL",
    "JOHNSON",
    "JOHNSTON",
    "JONKER",
    "JORDAN AEROSPACE",
    "JUNKERS",
    "JUNKERS PROFLY",
    "JUNQUA",
    "JURCA",
    "JUST",
    "K & S",
    "KADER",
    "KAISER",
    "KALINAUSKAS",
    "KAMAN",
    "KAMINSKAS",
    "KAMOV",
    "KANPUR",
    "KAPPA",
    "KARI",
    "KARI-KEEN",
    "KAWASAKI",
    "KAZAN",
    "KELEHER",
    "KELLY",
    "KELOWNA",
    "KESTREL",
    "KEUTHAN",
    "KEYSTONE",
    "KHRUNICHEV",
    "KIEGER",
    "KILLINGSWORTH",
    "KIMBALL",
    "KIMBREL",
    "KINETIC",
    "KING'S",
    "KITFOX",
    "KITPLANES FOR AFRICA",
    "KLEMM",
    "KLN",
    "KLS COMPOSITES",
    "KOLB",
    "KOREA AEROSPACE",
    "KOREAN AIR",
    "KOVACH-ELMENDORF",
    "KOVACS",
    "KREIDER-REISNER",
    "KUBICEK",
    "LA FRANCE",
    "LAIRD",
    "LAK",
    "LAKE",
    "LAMBACH",
    "LAMBERT",
    "LAMMER GEYER",
    "LANCAIR",
    "LANCASHIRE",
    "LANGE",
    "LANSHE",
    "LASER",
    "LAVEN",
    "LAVERDA",
    "LAVIASA",
    "LEARJET",
    "LEAVENS",
    "LEDERLIN",
    "LEGEND",
    "LEGEND FLYERS",
    "LEGER",
    "LEONARDO",
    "LET",
    "LEZA",
    "LEZA-LOCKWOOD",
    "LH AVIATION",
    "LIBERTY",
    "LICHTWERK",
    "LIGHT AERO",
    "LIGHT MINIATURE",
    "LIGHT WING",
    "LIGHTNING BUG",
    "LILIENTHAL",
    "LIPNUR",
    "LISA",
    "LISUNOV",
    "LITTLE WING",
    "LMAASA",
    "LOAD RANGER",
    "LOCKHEED",
    "LOCKHEED MARTIN",
    "LOCKHEED-AZCARATE",
    "LOCKWOOD",
    "LOEHLE",
    "LOMBARDI",
    "LONG",
    "LONGREN",
    "LOPRESTI",
    "LORAVIA",
    "LOT",
    "LOVING-WAYNE",
    "LTV",
    "LUCAS",
    "LUNDS TEKNISKE",
    "LUNDY",
    "LUSCOMBE",
    "LUSCOMBE-SILVAIRE",
    "LUTON",
    "LYAVIN",
    "M & D FLUGZEUGBAU",
    "MACAIR",
    "MACCHI",
    "MACDONALD",
    "MACHEN",
    "MACKEY",
    "MAD MAX AERO",
    "MAGNI",
    "MAKELAN",
    "MALMO",
    "MAPO",
    "MARA WING",
    "MARANDA",
    "MARCO",
    "MARGANSKI",
    "MARIE",
    "MARMANDE",
    "MARQUART",
    "MARSDEN",
    "MARSH",
    "MARTIN",
    "MAULE",
    "MAUPIN",
    "MAVERICK",
    "MAX HOLSTE",
    "MBB",
    "MBB-KAWASAKI",
    "MCCARLEY",
    "MCDONNELL",
    "MCDONNELL DOUGLAS",
    "MCKINNON",
    "MD HELICOPTERS",
    "MDB",
    "MEAD",
    "MELBOURNE",
    "MELEX",
    "MENAVIA",
    "MERCURY",
    "MERIDIONALI",
    "MERLIN",
    "MESSERSCHMITT",
    "MESSERSCHMITT-BOLKOW",
    "METEOR",
    "MEYER",
    "MEYERS",
    "MICCO",
    "MICROJET",
    "MICROLEVE",
    "MICROTURBO",
    "MID-CONTINENT",
    "MIDWEST AEROSPORT",
    "MIGNET",
    "MIKOYAN",
    "MIL",
    "MILES",
    "MILLER",
    "MILLICER",
    "MINI-IMP",
    "MIRAGE",
    "MITCHELL-PROCTER",
    "MITSUBISHI",
    "MOLNIYA",
    "MONG",
    "MONIOT",
    "MONNETT",
    "MONOCOUPE",
    "MONTAGNE",
    "MONTANA",
    "MOONEY",
    "MORANE-SAULNIER",
    "MORAVAN",
    "MORRISEY",
    "MORSE",
    "MOURA",
    "MRAZ",
    "MSW",
    "MUDRY",
    "MURPHY",
    "MURRAYAIR",
    "MUSTANG",
    "MVEN",
    "MXR",
    "MYASISHCHEV",
    "MYLIUS",
    "MYSKY",
    "NABERN",
    "NAI",
    "NAL",
    "NAMC",
    "NANCHANG",
    "NANJING",
    "NANJING UNIVERSITY",
    "NARDI",
    "NASH",
    "NATIONAL AERONAUTICS",
    "NATIONAL STEEL",
    "NAVION",
    "NDN",
    "NEICO",
    "NEIVA",
    "NEMESIS",
    "NESMITH",
    "NEW CENTURY",
    "NEW GLASAIR",
    "NEW GLASTAR",
    "NEW HORIZONS",
    "NEW MEYERS",
    "NEW STANDARD",
    "NEW ZEALAND",
    "NEXT AIRCRAFT",
    "NHI",
    "NICOLLIER",
    "NIEUPORT",
    "NIPPER",
    "NITSCHE",
    "NOIN",
    "NOORDUYN",
    "NORD",
    "NORDFLUG",
    "NORMAN",
    "NORMAND DUBE",
    "NORTH AMERICAN",
    "NORTH AMERICAN ROCKWELL",
    "NORTHERN",
    "NORTHROP",
    "NORTHROP GRUMMAN",
    "NORTHWEST TURBINE",
    "NOSTALGAIR",
    "NURTANIO",
    "NUSANTARA",
    "NUVENTURE",
    "NUWACO",
    "OAKLAND",
    "OBERLERCHNER",
    "ODESSA",
    "OGMA",
    "OLDFIELD",
    "OLYMPIC ULTRALIGHTS",
    "OMA SUD",
    "OMAC",
    "OMF",
    "OMNI",
    "OMNI-WELD",
    "ON MARK",
    "O'NEILL",
    "OPTICA",
    "OPTION AIR",
    "ORION",
    "ORLICAN",
    "OSKBES-MAI",
    "OSPREY",
    "P&M AVIATION",
    "PACAERO",
    "PACI",
    "PACIFIC AEROSPACE",
    "PACIFIC AIRMOTIVE",
    "PADC",
    "PAI",
    "PAKISTAN",
    "PANAVIA",
    "PANHA",
    "PANZL",
    "PAPA 51",
    "PARADISE",
    "PARAMOUNT ",
    "PARAVAR PARS",
    "PARKER",
    "PARNALL",
    "PARRISH",
    "PARTENAIR",
    "PARTENAVIA",
    "PASOTTI",
    "PATRIA",
    "PAULISTA",
    "PAWNEE",
    "PAXMAN'S",
    "PAYNE",
    "PAZMANY",
    "PCV",
    "PEGASE AERO",
    "PELEGRIN",
    "PENA",
    "PENNEC-LUCAS",
    "PERCIVAL",
    "PEREGRINE",
    "PEREIRA",
    "PERFORMANCE",
    "PETERSON",
    "PETROLINI",
    "PHENIX",
    "PHILLIPS",
    "PHILLIPS & POWIS",
    "PHOENIX",
    "PHOENIX AIR",
    "PHOENIX-AVIACOR",
    "PIAGGIO",
    "PIASECKI",
    "PIEL",
    "PIETENPOL",
    "PIK",
    "PILATUS",
    "PILATUS BRITTEN-NORMAN",
    "PIPER",
    "PIPISTREL",
    "PITCAIRN-CIERVA",
    "PITTS",
    "PLAN",
    "PLUMB",
    "POBER",
    "PODESVA",
    "POLIKARPOV",
    "POLITECHNIKA WARSZAWSKA",
    "PORTERFIELD",
    "POTEZ",
    "POTEZ AIR-FOUGA",
    "POTTIER",
    "POWELL",
    "PRACTAVIA",
    "PRESCOTT",
    "PRESTIGE",
    "PRIVATE EXPLORER",
    "PROCAER",
    "PRO-COMPOSITES",
    "PROFESSIONAL AVIATION",
    "PROGRESS",
    "PROGRESSIVE AERODYNE",
    "PROMAVIA",
    "PROTECH",
    "PROWLER",
    "PULSAR",
    "PUTZER",
    "PZL-MIELEC",
    "PZL-OKECIE",
    "PZL-SWIDNIK",
    "QINGDAO",
    "QUARTZ MOUNTAIN",
    "QUASAR",
    "QUERCY",
    "QUEST",
    "QUESTAIR",
    "QUICKIE",
    "QUIKKIT",
    "R & B",
    "RACA",
    "RADAB",
    "RAF",
    "RAGWING",
    "RAINBOW",
    "RAINBOW SKYREACH",
    "RAJ HAMSA",
    "RAND",
    "RANS",
    "RAVIN",
    "RAYTHEON",
    "REALITY",
    "REARWIN",
    "REDA",
    "REDFERN",
    "REFLEX",
    "REIMS",
    "REINER STEMME",
    "REINSDORF",
    "REMOS",
    "RENAISSANCE",
    "RENARD",
    "REPLICA PLANS",
    "REPUBLIC",
    "REVOLUTION",
    "RHEIN",
    "RHEIN-WEST-FLUG",
    "RIHN",
    "RILEY",
    "RLU",
    "ROBIN",
    "ROBINSON",
    "ROCK",
    "ROCKET",
    "ROCKWELL",
    "ROGERSON HILLER",
    "ROKO AERO",
    "ROLAND",
    "ROLLADEN-SCHNEIDER",
    "ROLLASON",
    "ROMAERO",
    "ROTARY AIR FORCE",
    "ROTEC",
    "ROTORSMART",
    "ROTORSPORT",
    "ROTORTEC",
    "ROTORWAY",
    "ROUCHAUD",
    "ROUSSEAU",
    "RTAF",
    "RUAG",
    "RUPERT",
    "RUSCHMEYER",
    "RUSSO",
    "RUTAN",
    "RYAN",
    "SAAB",
    "SAAB-FAIRCHILD",
    "SAASA",
    "SABCA",
    "SADLER",
    "SAFAT",
    "SAFRAN",
    "SAI",
    "SAINT GERMAIN",
    "SALVAY-STARK",
    "SAM AIRCRAFT",
    "SAMSUNG",
    "SAN",
    "SANDS",
    "SARGENT-FLETCHER",
    "SATIC",
    "SATURN-AVIA",
    "SAU",
    "SAUPER",
    "SAUSER",
    "SCALED",
    "SCAN",
    "SCANOR",
    "SCENIC",
    "SCHAFER",
    "SCHEIBE",
    "SCHEMPP-HIRTH",
    "SCHLEICHER",
    "SCHWEIZER",
    "SCINTEX",
    "SCOTTISH AVIATION",
    "SCWAL",
    "SEABIRD",
    "SEAFLIGHT",
    "SEASTAR",
    "SEAWIND",
    "SEGUIN",
    "SEPECAT",
    "SEQUOIA",
    "SERV-AERO",
    "SERVOPLANT",
    "SF",
    "SFERMA",
    "SG AVIATION",
    "SGAU",
    "SHAANXI",
    "SHADIN",
    "SHANGHAI",
    "SHANGHAI SIKORSKY",
    "SHARK AERO",
    "SHARK AIRCRAFT",
    "SHENYANG",
    "SHENYANG SAILPLANE",
    "SHERPA",
    "SHIJIAZHUANG",
    "SHIN MEIWA",
    "SHINMAYWA",
    "SHINN",
    "SHORT",
    "SHUYA",
    "SIAI-MARCHETTI",
    "SIAT",
    "SICHUAN LANTIAN",
    "SIKORSKY",
    "SILENCE",
    "SILHOUETTE",
    "SILVAIRE",
    "SILVERCRAFT",
    "SINDLINGER",
    "SINGAPORE",
    "SINO SWEARINGEN",
    "SIPA",
    "SIRAVIA",
    "SISLER",
    "SIVEL",
    "SKY RAIDER",
    "SKYCRAFT",
    "SKYDANCER",
    "SKYETON",
    "SKYFOX",
    "SKYGEAR",
    "SKYLINE",
    "SKYOTE AEROMARINE",
    "SKYSTAR",
    "SKYWOOD",
    "SLEPCEV",
    "SLICK",
    "SLINGSBY",
    "SLIPSTREAM",
    "SMAN",
    "SME",
    "SMITH",
    "SMITH (2)",
    "SMITH (3)",
    "SMITH AVIATION",
    "SMYTH",
    "SNOBIRD",
    "SNOW",
    "SOCA",
    "SOCATA",
    "SOKO",
    "SOKO-CNIAR",
    "SOLAR IMPULSE",
    "SOLOY",
    "SONEX",
    "SOPWITH",
    "SORRELL",
    "SPARTAN",
    "SPECTER",
    "SPECTRUM",
    "SPEEDTWIN",
    "SPENCER",
    "SPEZIO",
    "SPORT COPTER",
    "SPORT RACER",
    "SPORTAVIA-PUTZER",
    "SPORTINE AVIACIJA",
    "SPRATT",
    "SPRING",
    "SREYA",
    "SSH",
    "ST. CROIX",
    "ST. JUST",
    "STAMPE",
    "STARCK",
    "STARFIRE",
    "STARK",
    "STARKRAFT",
    "STARK-TREFETHEN",
    "STAR-LITE",
    "STARPAC",
    "STATLER",
    "STATUS AVIA",
    "STAUDACHER",
    "STEARMAN",
    "STEEN",
    "STEMME",
    "STEPHENS",
    "STERN",
    "STERN-MALLICK",
    "STEWART",
    "STINSON",
    "STITS",
    "STODDARD-HAMILTON",
    "STOLP",
    "STORCH AVIATION",
    "STORMAIRCRAFT",
    "STREAMLINE WELDING",
    "STRIPLIN",
    "STROJNIK",
    "SUD",
    "SUD-EST",
    "SUDFLUG",
    "SUD-OUEST",
    "SUKHOI",
    "SUMMIT",
    "SUNDERLAND",
    "SUPAPUP",
    "SUPER 18",
    "SUPER-CHIPMUNK",
    "SUPERMARINE",
    "SUPERMARINE AIRCRAFT",
    "SWEARINGEN",
    "SWICK",
    "S-WING",
    "SYMPHONY",
    "SYNAIRGIE",
    "SZD",
    "T & T AVIATION",
    "TAI",
    "TAIFUN",
    "TAIWAN DANCER",
    "TAM",
    "TAMARIND",
    "TANEJA",
    "TAPANEE",
    "TAYLOR",
    "TAYLOR KITS",
    "TAYLORCRAFT",
    "TAYLOR-YOUNG",
    "TBM",
    "TEAL",
    "TEAM ROCKET",
    "TEAM TANGO",
    "TECH'AERO ",
    "TECHNOAVIA",
    "TECHNOFLUG",
    "TECNAM",
    "TED SMITH",
    "TEMCO",
    "TENNESSEE VALLEY",
    "TERRAFUGIA",
    "TERR-MAR",
    "TERZI",
    "TEST",
    "TEXAS AIRPLANE",
    "TEXAS HELICOPTER",
    "TEXAS SPORT",
    "TEXTRON AIRLAND",
    "THATCHER",
    "THK",
    "THORP",
    "THRUSH",
    "THUNDER WINGS",
    "THURSTON",
    "TIGER",
    "TIME WARP",
    "TIPSY",
    "TITAN",
    "TL ULTRALIGHT",
    "TM AIRCRAFT",
    "TMM-AVIA",
    "TOMARK",
    "TOYOTA",
    "TRADEWIND TURBINES",
    "TRAGO MILLS",
    "TRANSALL",
    "TRANSAVIA",
    "TRAVEL AIR",
    "TRECKER",
    "TRIDAIR",
    "TRIDENT",
    "TRI-R",
    "TUPOLEV",
    "TURBINE CUBS",
    "TURBINE DESIGN",
    "TURNER",
    "TUSCO",
    "TWI",
    "UDET",
    "UETZ",
    "UFO",
    "UL-JIH",
    "ULLMANN",
    "ULTIMATE",
    "ULTRALEICHTBAU",
    "ULTRAVIA",
    "UMBAUGH",
    "UMBRA",
    "UNC",
    "UNIKOMTRANSO",
    "UNIS",
    "UNITED CANADA",
    "UNITED CONSULTANT",
    "UNIVERSAL COMPOSITE",
    "URBAN",
    "USTINOV",
    "UTVA",
    "VALENTIN",
    "VALLADEAU",
    "VALMET",
    "VALTION",
    "VANESSA AIR",
    "VAN'S",
    "VARDAX",
    "VARGA",
    "VAT",
    "VEB",
    "VELOCITY",
    "VENTURE",
    "VERHEES",
    "VERILITE",
    "VERTOL",
    "VFW",
    "VICKERS",
    "VICKERS-SLINGSBY",
    "VICTA",
    "VIDOR",
    "VIKING",
    "VIPER",
    "VISIONAIRE",
    "VITEK",
    "VOL MEDITERRANI",
    "VOLAIRCRAFT",
    "VOLANTE",
    "VOLMER",
    "VOLPAR",
    "VOUGHT",
    "VOUGHT-SIKORSKY",
    "VSR",
    "VSTOL",
    "VTOL AIRCRAFT",
    "VULCANAIR",
    "VULTEE",
    "WACO",
    "WACO CLASSIC",
    "WACO OHIO",
    "WAGAERO",
    "WALLERKOWSKI",
    "WAR",
    "WARNER",
    "WASSMER",
    "WATSON",
    "WEATHERLY",
    "WENDT",
    "WESTERN",
    "WESTLAND",
    "WET AERO",
    "WHATLEY",
    "WHEELER",
    "WHISPER",
    "WHITE",
    "WHITE LIGHTNING",
    "WILDEN",
    "WINDECKER",
    "WINDEXAIR",
    "WING",
    "WINGTIP TO WINGTIP",
    "WINNER",
    "WITTMAN",
    "WOLF",
    "WOLFSBERG",
    "WOODS",
    "WREN",
    "WUHAN",
    "WÜST",
    "WZL 3",
    "XIAN",
    "XTREMEAIR",
    "YAKIMA AEROSPORT",
    "YAKOVLEV",
    "ZENAIR",
    "ZENITH",
    "ZIVKO",
    "ZLIN",
    "ZLIN AVIATION"
  ];
